name: CI #github

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-service:
    runs-on: ubuntu-latest
    container:
      image: 756b-188-26-213-99.ngrok-free.app/api-iac:1.0.5
      env:
        AUTOCLOUD_API_URL: https://1595-188-26-213-99.ngrok-free.app
        # API Token Must Be Generated in AutoCloud for authentication
        # See https://docs.autocloud.io/generate-api-token for details on how to generate
        AUTOCLOUD_TOKEN: ${{ secrets.AUTOCLOUD_TOKEN }}
        # Configuration for blueprint
        # See https://docs.autocloud.io/catalog-service-pipeline-configuration for more details on how to configure output
        AUTOCLOUD_BLUEPRINT_ID: clod4e2da0000spt52gsvz36b
        AUTOCLOUD_BLUEPRINT_VARS:  |
          cps3bucket.additional_tag_map: {}
          cps3bucket.allow_encrypted_uploads_only: false
          cps3bucket.allow_ssl_requests_only: false
          cps3bucket.attributes: []
          cps3bucket.block_public_acls: true
          cps3bucket.block_public_policy: true
          cps3bucket.bucket_name: null
          cps3bucket.context: {"additional_tag_map":{},"attributes":[],"descriptor_formats":{},"enabled":true,"label_order":[],"labels_as_tags":["unset"],"tags":{}}
          cps3bucket.delimiter: null
          cps3bucket.descriptor_formats: {}
          cps3bucket.enabled: null
          cps3bucket.environment: null
          cps3bucket.id_length_limit: null
          cps3bucket.ignore_public_acls: true
          cps3bucket.kms_master_key_arn: ""
          cps3bucket.label_key_case: null
          cps3bucket.label_order: null
          cps3bucket.label_value_case: null
          cps3bucket.labels_as_tags: ["default"]
          cps3bucket.name: null
          cps3bucket.namespace: null
          cps3bucket.regex_replace_chars: null
          cps3bucket.restrict_public_buckets: true
          cps3bucket.s3_object_ownership: "ObjectWriter"
          cps3bucket.sse_algorithm: "AES256"
          cps3bucket.stage: null
          cps3bucket.tags: {}
          cps3bucket.tenant: null
          cps3bucket.versioning_enabled: true
      ports:
        - 80
      options: --cpus 1
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # entrypoint
      - name: Create a blueprint submission
        run: autocloud-submission
